"""add_user_permissions_and_qr_sessions

Revision ID: 0d7843eeb56a
Revises: d7c335071648
Create Date: 2026-09-25 00:19:34.169878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7843eeb56a'
down_revision: Union[str, Sequence[str], None] = 'd7c335071648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_upload_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_upload_sessions_expires_at'), 'qr_upload_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_qr_upload_sessions_token'), 'qr_upload_sessions', ['token'], unique=True)
    op.create_index(op.f('ix_qr_upload_sessions_user_id'), 'qr_upload_sessions', ['user_id'], unique=False)
    op.create_table('user_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('can_upload', sa.Boolean(), nullable=False),
    sa.Column('can_download', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.Column('can_rename', sa.Boolean(), nullable=False),
    sa.Column('can_share', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_qr_upload_sessions_user_id'), table_name='qr_upload_sessions')
    op.drop_index(op.f('ix_qr_upload_sessions_token'), table_name='qr_upload_sessions')
    op.drop_index(op.f('ix_qr_upload_sessions_expires_at'), table_name='qr_upload_sessions')
    op.drop_table('qr_upload_sessions')
    # ### end Alembic commands ###
