"""add media files

Revision ID: d7c335071648
Revises: 68a0adeb509d
Create Date: 2026-09-19 12:47:22.971927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c335071648'
down_revision: Union[str, Sequence[str], None] = '68a0adeb509d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('google_drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('google_drive_folder_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_files_google_drive_file_id'), 'media_files', ['google_drive_file_id'], unique=True)
    op.create_index(op.f('ix_media_files_google_drive_folder_id'), 'media_files', ['google_drive_folder_id'], unique=False)
    op.create_index(op.f('ix_media_files_owner_id'), 'media_files', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_files_owner_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_google_drive_folder_id'), table_name='media_files')
    op.drop_index(op.f('ix_media_files_google_drive_file_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
